services:
  marketing:
    build:
      context: .
      dockerfile: apps/marketing/Dockerfile
    image: relentnet-marketing:latest
    ports:
      - '${MARKETING_PORT:-3000}:80'
    restart: unless-stopped
