/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SowRouteImport } from './routes/sow'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as LegalDocIdRouteImport } from './routes/legal/$docId'
import { Route as ClientsSlugRouteImport } from './routes/clients/$slug'

const SowRoute = SowRouteImport.update({
  id: '/sow',
  path: '/sow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocIdRoute = LegalDocIdRouteImport.update({
  id: '/legal/$docId',
  path: '/legal/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsSlugRoute = ClientsSlugRouteImport.update({
  id: '/clients/$slug',
  path: '/clients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/inquire': typeof InquireRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
  '/clients/$slug': typeof ClientsSlugRoute
  '/legal/$docId': typeof LegalDocIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/inquire': typeof InquireRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
  '/clients/$slug': typeof ClientsSlugRoute
  '/legal/$docId': typeof LegalDocIdRoute
  '/clients': typeof ClientsIndexRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/inquire': typeof InquireRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
  '/clients/$slug': typeof ClientsSlugRoute
  '/legal/$docId': typeof LegalDocIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/inquire'
    | '/portal'
    | '/process'
    | '/sow'
    | '/clients/$slug'
    | '/legal/$docId'
    | '/clients/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic'
    | '/inquire'
    | '/portal'
    | '/process'
    | '/sow'
    | '/clients/$slug'
    | '/legal/$docId'
    | '/clients'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/inquire'
    | '/portal'
    | '/process'
    | '/sow'
    | '/clients/$slug'
    | '/legal/$docId'
    | '/clients/'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  InquireRoute: typeof InquireRoute
  PortalRoute: typeof PortalRoute
  ProcessRoute: typeof ProcessRoute
  SowRoute: typeof SowRoute
  ClientsSlugRoute: typeof ClientsSlugRoute
  LegalDocIdRoute: typeof LegalDocIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sow': {
      id: '/sow'
      path: '/sow'
      fullPath: '/sow'
      preLoaderRoute: typeof SowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$docId': {
      id: '/legal/$docId'
      path: '/legal/$docId'
      fullPath: '/legal/$docId'
      preLoaderRoute: typeof LegalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$slug': {
      id: '/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/clients/$slug'
      preLoaderRoute: typeof ClientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  InquireRoute: InquireRoute,
  PortalRoute: PortalRoute,
  ProcessRoute: ProcessRoute,
  SowRoute: SowRoute,
  ClientsSlugRoute: ClientsSlugRoute,
  LegalDocIdRoute: LegalDocIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
